---
    root: true
    parserOptions: 
        sourceType: module
        ecmaVersion: 8
        ecmaFeatures: 
            jsx: true
            dimpliedStrict: true
    rules: 
        semi: 2
        brace-style: 
            - error
            - 1tbs
            - allowSingleLine: true
        indent: 
            - error
            - tab
    env: 
        browser: true
        node: true
        es6: true
    

