language: node_js
node_js:
  - "8"
  - "7"

sudo: false

cache: npm

branches:
  only:
    - master

install:
  - npm install

script:
  - ./node_modules/standard/bin/cmd.js --fix
  - ./scripts/build.sh

notifications:
  email: false
