language: node_js
node_js:
  - "8"
  - "7"

sudo: false

cache: yarn

branches:
  only:
    - master

install:
  - yarn install

script:
  - ./node_modules/standard/bin/cmd.js --fix
  - yarn build

notifications:
  email: false
